### ISSUE TITLE
DeepOCSORT: missing 2 required positional arguments: 'w' and 'h when using 'centroid' as associate function 

### ISSUE THREAD

**Issue by grassjelly** [mikel-brostrom/yolo_tracking#1372]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

I'm using DeepOCSort as a tracker with an external object detector. The tracking works for a few seconds but hits an error after a while. I think it's when no objects are detected on the frame.

Error:
File "/usr/local/lib/python3.8/dist-packages/boxmot/trackers/deepocsort/deep_ocsort.py", line 462, in update
object-tracker  | [tracked_bbox_publisher.py-1]     iou_left = self.asso_func(left_dets, left_trks)
object-tracker  | [tracked_bbox_publisher.py-1] TypeError: centroid_batch() missing 2 required positional arguments: 'w' and 'h

### Environment

- Yolo Tracking v 10.0.52

### Minimal Reproducible Example

This is my update function

    def update(self, detections, img) :
        tracked_objects = []
        if len(detections) == 0:
            detections = np.empty((0, 6))
        else:
            detections = np.array(detections)

        tracks = self._tracker.update(detections, img)
        if tracks.shape[0] != 0:
            xyxys = tracks[:, 0:4].astype('int') # float64 to int
            ids = tracks[:, 4].astype('int') # float64 to int
            confs = tracks[:, 5]
            clss = tracks[:, 6].astype('int') # float64 to int

            for xyxy, id, conf, cls in zip(xyxys, ids, confs, clss):
                tracked_objects.append([
                    xyxy[0],
                    xyxy[1],
                    xyxy[2],
                    xyxy[3],
                    id,
                    cls,
                    conf
                ])

        return tracked_objects

and here's my config:

```
DEEP_OC_SORT:
  reid_weights: 'RESNET'
  device_id: 0                # Cuda GPU ID
  fp16: True                  # Enable FP16
  max_age: 1200
  per_class: True
  det_thresh: 0.3
  max_age: 30
  min_hits: 3
  iou_threshold: 0.3
  delta_t: 3
  asso_func: "centroid" #https://github.com/mikel-brostrom/yolo_tracking/issues/1246
  inertia: 0.2
  w_association_emb: 0.5
  alpha_fixed_emb: 0.95
  aw_param: 0.5
  embedding_off: False
  cmc_off: False
  aw_off: False
  new_kf_off: False
```
