### ISSUE TITLE
Supported GPU version is not

### ISSUE THREAD

**Issue by the-cat-crying** [mikel-brostrom/yolo_tracking#1424]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Supported GPU version is not

**Comment by mikel-brostrom** [comment]
You are right. I accidentally deleted the possibility of installing GPU compatible version of torch:

https://github.com/mikel-brostrom/yolo_tracking/blob/281a6be3fda055986a8f93a8c163d691e565e1ae/pyproject.toml#L42-L49

Fixing this. Thanks for pointing out 😄

**Comment by mikel-brostrom** [comment]
This should have now been fixed. As seen here in `pyproject.toml`:

```toml
[tool.poetry.dependencies]
python = "^3.8"
filterpy = "^1.4.5"
gdown = "^5.1.0"
lapx = "^0.5.5"
loguru = "^0.7.2"
numpy = "1.24.4"
pyyaml = "^6.0.1"
regex = "^2024.0.0"
yacs = "^0.1.8"
scikit-learn = "^1.3.0"
pandas = "^2.0.0"
opencv-python = "^4.7.0"
ftfy = "^6.1.3"
gitpython = "^3.1.42"
torch = [
    {version = "^2.2.1", source="pypi", markers = "sys_platform == 'darwin'"},
    {version = "^2.2.1+cu113", markers = "sys_platform == 'linux' or sys_platform == 'win32'"}
]
torchvision = [
    {version = "^0.17.1", source="pypi", markers = "sys_platform == 'darwin'"},
    {version = "^0.17.1+cu113", markers = "sys_platform == 'linux' or sys_platform == 'win32'"}
]
```

`CUDA` enable versions of `torch` and `torchvision` are installed for linux and windows
